VG-2: Time tracking
x-team/vetting-games pull request #1
Opened 2022-11-08 17:17 UTC by Arthaclarius

## Ticket

[VG-2 | Time tracking](https://x-team-internal.atlassian.net/browse/VG-2)

## Description

### Basic Set up

- Added a basic setup including more description and how to get started to the `README.md`.
- Included Tailwind to style with ease.
- Added prettier and eslint for basic formatting and linting, both with the default configuration.
- Added commands to run format and lint with prettier and eslint.

### Time Tracking Lib

- Coded a small library for time-tracking in React.
- Added a React Context to control time tracking through the app.
- Added controls for tracking tasks and stopping tracking.

### Time Tracking Controls

- Added UI elements to control which tasks are tracked.
- Added UI element to stop tracking time.
- Display tracked data.
- Stored tracked data in local storage.

#### Demo

[VG-2: Time tracking Demo](https://vimeo.com/768635477/6a29bc73f7)

2022-11-15 19:50 UTC, smaryka requested changes
you should get Francisco to review as well.

2022-11-15 19:50 UTC, smaryka commented on src/lib/time-traking/Provider.tsx
> +import { FC, ReactNode } from "react";
You should rename the directory to fix the typo `traking` ==> `tracking`

2022-11-17 07:55 UTC, Arthaclarius commented on src/lib/time-traking/Provider.tsx
> +import { FC, ReactNode } from "react";
Fixed

2022-11-21 19:08 UTC, smaryka approved these changes

2022-11-23 01:42 UTC, merged